### ISSUE TITLE
Formatting on invoices is a bit weird

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#110]
![image](https://user-images.githubusercontent.com/14950489/172031622-7316eefb-0bb3-4ecd-a1ad-872ceec04e8c.png)

**Comment by Wyn-Price** [comment]
How's this:
![image](https://user-images.githubusercontent.com/15876682/180657626-89ad0227-c482-403a-b7e8-48b0ebebc3e5.png)

**Comment by NeusFear** [comment]
Looks good to me, I’ll have my dad review
