### ISSUE TITLE
Edit Cut Instructions Modal Needs New Fields

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#111]
Needs:
- instructions taken by string field
- person giving instructions (since it's not always the same name as an eater)
- date taken (not automatic): make a string field but with a button to the right of it that fills the current date (they don't want it to update the date unless they specifically tell it to update)

**Comment by Wyn-Price** [comment]
> instructions taken by string field

what does this mean?

**Comment by NeusFear** [comment]
A string field labeled "instructions taken by"

**Comment by NeusFear** [comment]
Would also be nice if we saved previous names for use later
