### ISSUE TITLE
Reforatting and additions to Cut Sheet pdf

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#112]
I have added an example on the repo [here](https://github.com/NeusFear/CountryHomeMeatsCo/blob/main/db_structure/Cut%20Sheet%20Template.pdf)

Key Notes:
- Half of Halves should be their own sheets so we can remove the sharer's name and only have one name on each sheet
- Move portion info in place of the second eater's name and add info referenced in #111 to be displayed underneath
- Abbreviate a few things: Chicken Fry -> CF Hamburger -> HB Tenderized -> T
- Move Take home weight and add freezer to bottom (remove lines for number since it's more of a place to calculate by hand the weight since you don't want to charge for tray weights and things)
- display the dressed weight
- other size and font-weight changes - see example
- red number next to bringer name is the number of beef that bringer brought on the day that animal was killed
- mind the spacing of items (the blank area at the bottom is intentional)
- add Invoice Number

**Comment by NeusFear** [comment]
Also Note: Add liver bad comment to comments section if it's bad. see #97 first

**Comment by Wyn-Price** [comment]
So,
  - With the half of halves having their own sheet, would it just be the cut instructions from the main eater? So essentially the only difference between a main eater cut instructions and a sharer cut instructions is the name?
  - Would the red number next to the bringers name be for pork too? or just beef?. Is it essentially the number of animals the bringer had "scheduled" to be killed the date that the invoice's animal was killed?

**Comment by NeusFear** [comment]
* yes basically
* yes just number of animals killed

**Comment by Wyn-Price** [comment]
Take a look at: [chmtest.pdf](https://github.com/NeusFear/CountryHomeMeatsCo/files/9176835/tttttt.pdf) to see if it's how you want.
Note that the following haven't been added:
 - Abbreviate a few things: Chicken Fry -> CF Hamburger -> HB Tenderized -> T
 - other size and font-weight changes - see example
 - red number next to bringer name is the number of beef that bringer brought on the day that animal was killed

**Comment by NeusFear** [comment]
Looks pretty good so far

**Comment by Wyn-Price** [comment]
I've added all the suggestions now: [chm.pdf](https://github.com/NeusFear/CountryHomeMeatsCo/files/9182256/tttttt.pdf)

**Comment by NeusFear** [comment]
Does the reason for liver bad get added to comments?

**Comment by Wyn-Price** [comment]
It does now
![image](https://user-images.githubusercontent.com/15876682/180814783-158d73d4-a043-4b78-a35f-bd3d77d8a3c7.png)

**Comment by NeusFear** [comment]
Put it down with the comments section lol
