### ISSUE TITLE
Search button is useless - we should remove it

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#115]
I know that you can just hit enter but the button may as well work

**Comment by Wyn-Price** [comment]
There is no "searching". Searching is done as you type. Maybe we should remove the button?

**Comment by NeusFear** [comment]
Yeah I guess that makes sense

**Comment by Wyn-Price** [comment]
Closed in 2350cd5dbce9e3c5d2a2304235df1cae7b75edf8
