### ISSUE TITLE
Remove bone out checkboxes

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#54]
Explanation of what needs to happen:

Club steaks are bone in and ribeye is the bone out version of club steaks

Tbone is bone in loin and bone out is strips and fillets. Basically if it's blank it's a tbone and add option for bone out

**Comment by NeusFear** [comment]
For club steaks if it's blank it's not bone out. If it's ribeye then it's bone in

**Comment by Wyn-Price** [comment]
Gotcha
