### ISSUE TITLE
Need a way to delete an invoice

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#81]
Idk why, but they want it. Might talk to them and find out why first.

**Comment by Wyn-Price** [comment]
If you re-generate an animals invoices, it'll remove the previous invoices

**Comment by NeusFear** [comment]
I think that should be better clarified too, but also we need a way to regenerate specific invoices. How about when the invoices have been generated before the button "generate" changes to "regenerate invoices" and we should also add a way to regenerate a specific invoice, could just be a delete and a refresh icon on the invoice in the lsit
