### ISSUE TITLE
Take home percentages are not correct

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#87]

**Comment by Wyn-Price** [comment]
The Take Home field in the invoice page is for just that invoice, not for the whole animal. The % also is right, it's the % of the dress weight. I can make it so it's the % of the dress portion if you want

**Comment by NeusFear** [comment]
ok

**Comment by NeusFear** [comment]
I read wrong, it's not just for 1/2 beef it's just in general apparently
