### ISSUE TITLE
Add identifiers to in the cooler page

### ISSUE THREAD

**Issue by NeusFear** [NeusFear/CountryHomeMeatsCo#90]
He changed his mind, he does want the identifiers here

**Comment by Wyn-Price** [comment]
Cut instruction identifiers?

**Comment by NeusFear** [comment]
yes

**Comment by Wyn-Price** [comment]
Also, should we show half of half users on the cooler page?

**Comment by Wyn-Price** [comment]
nvm, saw the other issue
